#!/bin/sh
#vim:filetype=sh
	

dark_or_light(){
dark_light=$(echo -e "Dark\nLight" | dmenu -i -p "Theme?")
	case $dark_light in
		'Dark')theme=$( ls $HOME/.local/lib/python3.10/site-packages/pywal/colorschemes/dark/ | sed 's/\.json//' | dmenu -i ) && wal --theme $theme && $HOME/scripts/reload_theme  &&  feh --bg-scale $(find $HOME/wallpapers/dark/* | sxiv -tio)
 ;;
		'Light')theme=$( ls $HOME/.local/lib/python3.10/site-packages/pywal/colorschemes/light/ | sed 's/\.json//' | dmenu -i ) && wal -l --theme $theme && $HOME/scripts/reload_theme && feh --bg-scale   $(find $HOME/wallpapers/light/* | sxiv -tio)
;;
	esac
}
wallpapset(){
	dark_light=$(echo -e "Dark\nLight" | dmenu -i -p "Theme?")
		case $dark_light in
			'Light')wallp=$(find $HOME/wallpapers/*/* | sxiv -tio) &&\
				       wal -l -i $wallp
			$HOME/scripts/reload_theme
				 ;;
			'Dark')wallp=$(find $HOME/wallpapers/*/* | sxiv -tio) &&\
				      wal  -i $wallp
			$HOME/scripts/reload_theme
		esac
}
theme_wallpaper=$(echo -e "Premade Theme\nWallpaper" | dmenu -i)
case $theme_wallpaper in
	'Premade Theme')dark_or_light;;
	'Wallpaper')wallpapset;;
esac


