#!/bin/sh
#vim:filetype=sh
if pgrep  xmonad; then
#pgrep -x bar && pkill bar 
xmonad --recompile && xmonad --restart
elif pgrep -x bspwm;then
       $HOME/scripts/lemonbar/bar.sh
	bspc config normal_border_color "$background"
	bspc config focused_border_color "$foreground"
elif pgrep -x dwm;then
       $HOME/scripts/lemonbar/dwm/bar.sh
fi

if pgrep emacs;then
    emacsclient --eval '(reload-dotemacs-file)'
fi

qutebrowser_reload.py
