#!/bin/sh
exec xset r rate 300 100 &
xrdb -merge ~/.config/X11/Xresources &
emacs --daemon >/dev/null 2>&1 &
wal -R & 
dunst &
exec clipmenud &
exec xmodmap ~/.config/xmodmap/capstoctrl >log 2>&1 & 
xrandr -q | grep HDMI && ~/.screenlayout/bigscreen.sh
xrandr --size 720x525 &
blueman-applet &
nm-applet &
#xbindkeys &
xcape &
kill -9  $HOME/.config/bspwm/bspwmrc
pkill -9 -f $HOME/.config/bspwm/bar_click.sh
killall sxhkd 
#killall compton
killall xtitle
sxhkd &
bspc config window_gap 0
#if test -f /tmp/bspwm_gapsize; then
	#bspc config window_gap $(cat /tmp/bspwm_gapsize)
#fi
#bspc config window_gap 0


#if [ $( bspc query -M --names | wc -l ) -eq 1 ];then
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 \%{B}
#elif [ $( bspc query -M --names | wc -l ) -eq 2 ];then
	#$HOME/.config/bspwm/docklayout.sh
	#bspc monitor  "DP-1" -d 1 2 3 4 5\ %{B}
	#bspc monitor  "eDP-1" -d 6 7 8 9 10\ %{B}
#fi

bspc config border_width         1

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
exec ~/.fehbg &
pkill lemonbar
pkill dzen
exec xset r rate 300 100 &
exec xmodmap $HOME/.config/xmodmap/capstoctrl &
if [pgrep -x xcape]; then
	xcape &
	~/scripts/keybinds/hypers
fi
exec wal -R &
exec dunst &
bspc config normal_border_color "#000000"
bspc config focused_border_color "#EEE8D5"


bspc rule -a Inkscape desktop='^5' focus=on follow=on
bspc rule -a Emacs state=tiled manage=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh focus=on state=floating
bspc rule -a Zathura state=tiled manage=on
bspc rule -a zathura state=tiled manage=on
bspc rule -a Firefox state=tiled 
bspc rule -a Toplevel state=tiled 
bspc rule -a qutebrowser state=tiled follow=on
bspc rule -a lemonbar layer=below
bspc rule -a Bar layer=below
$HOME/.config/bspwm/applets &
pkill -f $HOME/scripts/lemonbar/bspwm/bar_click.sh
$HOME/scripts/lemonbar/bspwm/bar_click.sh &
#picom &
#~/scripts/keybinds/hypers
