myKeys :: [(String, X ())]
myKeys =
  [ ("M-<return>", spawn $ Xmonad.terminal conf)
  ,("M-<Space>", spawn "/home/david/scripts/dmenu_run_history")
  ,("M-d", spawn "clipmenu")
  ,("M-q", kill)
  ,("M-S-<Tab>", sendMessage NextLayout)
  ,("M-S-<Space>", setLayout $ Xmonad.layoutHook conf)
  ,("M-S-f", spawn "st -e ranger")
  ,("M-S-m", spawn "st -e neomutt")
  ,("M-S-n", spawn "$HOME/scripts/mpd/mpdmenu")
  ,("M-j", windows W.focusDown)
  ,("M-k", windows W.focusUp)
  ,("M-m", windows W.focusMaster)
  ,("M-S-j", windows W.swapDown)
  ,("M-S-k", windows W.swapUp)
  ,("M-S-<equal>", sendMessage $ ToggleGaps)
  ,("M-h", sendMessage Shrink)
  ,("M-l", sendMessage Expand)
  ,("M-f", sendMessage $ XMonad.Layout.MultiToggle.Toggle FULL)
  ,("M-t",  withFocused $ windows . W.sink)
    , "<XF86AudioLowerVolume>"   , spawn "$HOME/scripts/keybinds/volume.sh down")
    , "<XF86AudioRaiseVolume>", spawn "$HOME/scripts/keybinds/volume.sh up")
    , "<XF86AudioMute>", spawn "$HOME/scripts/keybinds/volume.sh toggle")
    , ("M-<grave>", namedScratchpadAction myScratchPads "terminal")
    , ( "M-S-n", namedScratchpadAction myScratchPads "music")
    , ("M-S-t", namedScratchpadAction myScratchPads "htop")
    , ("M-,", sendMessage (IncMasterN 1))
    ,("M-b", sendMessage ToggleStruts)
  ]
