#!/bin/sh
#vim:filetype=sh
while read -r line; do
	case $line in
		"C*")
			  wm_infos=""
		    IFS=':'
		    set -- ${line#?}
		    while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    O*)
                        # focused occupied desktop
                        wm_infos="$wm_infos$occupied_focus"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="$wm_infos$empty_focus"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="$wm_infos%{B$bg_urgenttags}%{F$fg_urgenttags}$occupied_focus%{B$bg_tags}%{F$fg_tags}"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="$wm_infos%{A:bspc desktop -f ${name}:}$occupied%{A}"
                        ;;
                    f*)
                        # free desktop
                        wm_infos="$wm_infos%{A:bspc desktop -f ${name}:}$empty%{A}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos%{A:bspc desktop -f ${name}:}%{B$bg_urgenttags}%{F$fg_urgenttags}$occupied%{B$bg_tags}%{F$fg_tags}%{A}"
                        ;;
		"W*")
			#bspwm events
			;;
		"m*")
			#mail events
			;;
		"M*")
			#music events
			;;
	esac
