#!/bin/sh
#vim:filetype=sh
source $HOME/.cache/wal/colors.sh
killall lemonbar
killall mpc
FONT="Iosevka Nerd Font:size=9"
HEIGHT=15

BG=$background
FG=$foreground
HEIGHT=15
WIDTH=$( xdpyinfo  | grep -i 'dimensions:' | sed 's:x:\ :' | awk '{print $2}' ) 

BarWidth=600
BarPosX=$( expr "$WIDTH" - $BarWidth )
#FONT="Font Awesome 5 Free Solid:size=9"
FONT="Iosevka Nerd Font:size=10"




cat | while IFS= read -r line; do
  printf '%s\n' "$line" | sed\
	  -e  "s/%N NSP %n\ //"\
	  -e "s/%C/%{F$foreground}%{B$background}/"\
	  -e 's/%c/%{F}%{B}/'\
	  -e "s/%H/%{F$background}%{B$color8}/g"\
	  -e 's/%h/%{F}%{B}/g'\
	  -e "s/%N/%{F$background}%{B$foreground}/g"\
	  -e 's/%n/%{F}%{B}/g'
done  | lemonbar  -B $background -g x$HEIGHT &

$HOME/scripts/lemonbar/xmonad/modules 2>/dev/null |\
		lemonbar  \
		-g $BarWidth\x$HEIGHT+$BarPosX+0 \
		-f "$FONT" \
		-B $BG \
		-F $FG\
		& wait $!

