#!/bin/sh
#vim:filetype=sh
source $HOME/.cache/wal/colors.sh
killall lemonbar
killall mpc
kill -s SIGKILL $(cat /tmp/xmonad/pid_xmonad)
#kill -s SIGINT
#FONT1="CozetteVector:size=10"
HEIGHT=15
#FONT2="Font Awesome 5 Free Solid:size=9"
FONT="Hack Nerd Font:size=9"
#FONT2="Iosevka Nerd Font:size=10"

BG=$background
FG=$foreground
HEIGHT=15
WIDTH=$( xdpyinfo  | grep -i 'dimensions:' | sed 's:x:\ :' | awk '{print $2}' ) 

BarWidth=600
BarPosX=$( expr "$WIDTH" - $BarWidth )
#FONT="Font Awesome 5 Free Solid:size=9"

updatebat(){
	extbatstatus=$(cat $extbatfile)
	if [ $extbatstatus == 0 ]; then
	echo 1 > $extbatfile
	else
	echo 0 > $extbatfile
	fi
	getBattery > $batfile
	main
}



cat | while IFS= read -r line; do
  	 sed\
	  -e  "s/%N NSP %n\ //"\
	  -e "s/%C/%{F$foreground}%{B$background}/"\
	  -e 's/%c/%{F}%{B}/'\
	  -e "s/%H/%{F$background}%{B$color8}/g"\
	  -e 's/%h/%{F}%{B}/g'\
	  -e "s/%N/%{F$background}%{B$foreground}/g"\
	  -e 's/%n/%{F}%{B}/g' <<< $line
done  | lemonbar  -B $background -g x$HEIGHT -f "$FONT" &

sleep 0.1

$HOME/scripts/lemonbar/xmonad/modules 2>/dev/null | lemonbar -p -g $BarWidth\x$HEIGHT+$BarPosX+0  -f "Font Awesome" -f "Iosevka Nerd Font:size=10"  -B $BG  -F $FG | sh
