#!/usr/bin/env bash

_rofi() {
  rofi -sep '|' -columns 6 -lines 1 -disable-history true -cycle true \
    -theme ~/.config/rofi/theme/rofi-simplemenu.rasi -width 80 -height 200 \
    -dmenu -font "Hack Nerd Font 40" "$@"
}

play_exit_sound() {
  ffplay -nodisp -loglevel quiet -vn -t 6.5 -autoexit \
    $XDG_DATA_HOME/sounds/場面転換サウンドロゴ_002.m4a
}

choice=$(echo -n "|||||" | _rofi -mesg "<span face='ClearSans' font='30' weight='bold'>Goodbye, Japorized!</span>")

case "$choice" in
  )
    slock
    ;;
  )
    ~/.bin/displaysleep
    ;;
    systemctl suspend
    ;;
  )
    choice=$(echo "No|Yes" | _rofi -mesg "<span face='ClearSans' font='30' weight='bold'>Logging out. Are you sure?</span>")
    if [ "$choice" = "Yes" ]; then
      cleandesktop.sh
      play_exit_sound
      bspc quit
    fi
    ;;
  )
    choice=$(echo "No|Yes" | _rofi -mesg "<span face='ClearSans' font='30' weight='bold'>Rebooting. Are you sure?</span>")
    if [ "$choice" = "Yes" ]; then
      play_exit_sound
      systemctl reboot
    fi
    ;;
  )
    choice=$(echo "No|Yes" | _rofi -mesg "<span face='ClearSans' font='30' weight='bold'>Powering off. Are you sure?</span>")
    if [ "$choice" = "Yes" ]; then
      play_exit_sound
      systemctl poweroff
    fi
    ;;
esac
